/*********************************************************************
*                     SEGGER Microcontroller GmbH                    *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        emWin Font Converter (NXP) version 6.10                     *
*        Compiled Dec 19 2019, 16:35:08                              *
*                                                                    *
*        (c) 1998 - 2019 Segger Microcontroller GmbH                 *
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: font_size16.c                                         *
* Font:        µ¸¿ò                                                  *
* Height:      16                                                    *
*                                                                    *
**********************************************************************
*                                                                    *
* Initial font height:  16                                           *
* Character disabled:  0xA2 (162)                                    *
* Range disabled:       0000 - FFFF                                  *
* Character enabled:   0x30 (48)                                     *
* Character enabled:   0x70 (112)                                    *
* Character disabled:  0x70 (112)                                    *
* Character enabled:   0x70 (112)                                    *
* Character disabled:  0x70 (112)                                    *
* Character enabled:   0xABF0 (44016)                                *
* Character disabled:  0xABF0 (44016)                                *
* Character enabled:   0xAC10 (44048)                                *
* Character enabled:   0xAC00 (44032)                                *
* Character disabled:  0xAC00 (44032)                                *
* Character enabled:   0xAC00 (44032)                                *
* Character enabled:   0xAC01 (44033)                                *
* Character enabled:   0xAC04 (44036)                                *
* Character enabled:   0xAC06 (44038)                                *
* Character disabled:  0xAC06 (44038)                                *
* Character disabled:  0xAC04 (44036)                                *
* Character disabled:  0xAC00 (44032)                                *
* Character enabled:   0xAC00 (44032)                                *
* Character disabled:  0xAC10 (44048)                                *
* Character disabled:  0xAC00 (44032)                                *
* Character disabled:  0xAC01 (44033)                                *
* Character enabled:   0xC815 (51221)                                *
* Character enabled:   0xCE21 (52769)                                *
* Character enabled:   0xC0C1 (49345)                                *
* Character enabled:   0xD0DC (53468)                                *
* Pixel index of character 0xD0DC (53468) at 9/10 set to 0           *
* Character enabled:   0xC774 (51060)                                *
* Character enabled:   0xBCA4 (48292)                                *
* Character enabled:   0xD2B8 (53944)                                *
* Character enabled:   0xBCF4 (48372)                                *
* Character enabled:   0xD638 (54840)                                *
* Character disabled:  0xD638 (54840)                                *
* Character enabled:   0xD638 (54840)                                *
* Character enabled:   0x20 (32)                                     *
* Character enabled:   0x2E (46)                                     *
* Character enabled:   0x2B (43)                                     *
* Character enabled:   0x2D (45)                                     *
* Character enabled:   0x2A (42)                                     *
* Character enabled:   0x1E (30)                                     *
* Character enabled:   0x1F (31)                                     *
* Character enabled:   0xC124 (49444)                                *
* Character enabled:   0xC2DC (49884)                                *
* Character enabled:   0xC2A4 (49828)                                *
* Character enabled:   0xD15C (53596)                                *
* Character enabled:   0xBA85 (47749)                                *
* Character enabled:   0xB839 (47161)                                *
* Pixel index of character 0xB839 (47161) at 8/7 set to 0            *
* Pixel index of character 0xB839 (47161) at 9/7 set to 0            *
* Character enabled:   0xACC4 (44228)                                *
*                                                                    *
**********************************************************************
*/

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

/* The following line needs to be included in any file selecting the
   font.
*/
extern GUI_CONST_STORAGE GUI_FONT GUI_Fontfont_size16;

/* Start of unicode area <Basic Latin> */
static GUI_CONST_STORAGE unsigned char acGUI_Fontfont_size16_001E[ 14] = { /* code 001E, <control> */
  ___X____,
  ___X____,
  ___X____,
  __XXX___,
  __XXX___,
  __XXX___,
  __XXX___,
  _XXXXX__,
  _XXXXX__,
  _XXXXX__,
  _XXXXX__,
  XXXXXXX_,
  XXXXXXX_,
  XXXXXXX_};

static GUI_CONST_STORAGE unsigned char acGUI_Fontfont_size16_001F[ 14] = { /* code 001F, <control> */
  XXXXXXX_,
  XXXXXXX_,
  XXXXXXX_,
  _XXXXX__,
  _XXXXX__,
  _XXXXX__,
  _XXXXX__,
  __XXX___,
  __XXX___,
  __XXX___,
  __XXX___,
  ___X____,
  ___X____,
  ___X____};

static GUI_CONST_STORAGE unsigned char acGUI_Fontfont_size16_0020[  1] = { /* code 0020, SPACE */
  ________};

static GUI_CONST_STORAGE unsigned char acGUI_Fontfont_size16_002A[  5] = { /* code 002A, ASTERISK */
  __X_____,
  __X_____,
  XXXXX___,
  __X_____,
  _X_X____};

static GUI_CONST_STORAGE unsigned char acGUI_Fontfont_size16_002B[  7] = { /* code 002B, PLUS SIGN */
  ___X____,
  ___X____,
  ___X____,
  XXXXXXX_,
  ___X____,
  ___X____,
  ___X____};

static GUI_CONST_STORAGE unsigned char acGUI_Fontfont_size16_002D[  1] = { /* code 002D, HYPHEN-MINUS */
  XXXXXXX_};

static GUI_CONST_STORAGE unsigned char acGUI_Fontfont_size16_002E[  2] = { /* code 002E, FULL STOP */
  X_______,
  X_______};

static GUI_CONST_STORAGE unsigned char acGUI_Fontfont_size16_0030[ 12] = { /* code 0030, DIGIT ZERO */
  __XXX___,
  _X___X__,
  X_____X_,
  X_____X_,
  X_____X_,
  X_____X_,
  X_____X_,
  X_____X_,
  X_____X_,
  X_____X_,
  _X___X__,
  __XXX___};

static GUI_CONST_STORAGE unsigned char acGUI_Fontfont_size16_0031[ 12] = { /* code 0031, DIGIT ONE */
  __X_____,
  XXX_____,
  __X_____,
  __X_____,
  __X_____,
  __X_____,
  __X_____,
  __X_____,
  __X_____,
  __X_____,
  __X_____,
  __X_____};

static GUI_CONST_STORAGE unsigned char acGUI_Fontfont_size16_0032[ 12] = { /* code 0032, DIGIT TWO */
  __XXX___,
  _X___X__,
  X_____X_,
  X_____X_,
  ______X_,
  _____X__,
  ___XX___,
  __X_____,
  _X______,
  X_______,
  X_______,
  XXXXXXX_};

static GUI_CONST_STORAGE unsigned char acGUI_Fontfont_size16_0033[ 12] = { /* code 0033, DIGIT THREE */
  __XXX___,
  _X___X__,
  X_____X_,
  ______X_,
  _____X__,
  __XXX___,
  _____X__,
  ______X_,
  ______X_,
  X_____X_,
  _X___X__,
  __XXX___};

static GUI_CONST_STORAGE unsigned char acGUI_Fontfont_size16_0034[ 12] = { /* code 0034, DIGIT FOUR */
  ____XX__,
  ____XX__,
  ___X_X__,
  ___X_X__,
  __X__X__,
  __X__X__,
  _X___X__,
  _X___X__,
  XXXXXXXX,
  _____X__,
  _____X__,
  _____X__};

static GUI_CONST_STORAGE unsigned char acGUI_Fontfont_size16_0035[ 12] = { /* code 0035, DIGIT FIVE */
  _XXXXXXX,
  _X______,
  _X______,
  _X______,
  _X_XXX__,
  _XX___X_,
  _X_____X,
  _______X,
  _______X,
  X______X,
  _X____X_,
  __XXXX__};

static GUI_CONST_STORAGE unsigned char acGUI_Fontfont_size16_0036[ 12] = { /* code 0036, DIGIT SIX */
  __XXX___,
  _X___X__,
  X_____X_,
  X_______,
  X_XXX___,
  XX___X__,
  X_____X_,
  X_____X_,
  X_____X_,
  X_____X_,
  _X___X__,
  __XXX___};

static GUI_CONST_STORAGE unsigned char acGUI_Fontfont_size16_0037[ 12] = { /* code 0037, DIGIT SEVEN */
  XXXXXXX_,
  ______X_,
  _____X__,
  _____X__,
  ____X___,
  ____X___,
  ____X___,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ___X____};

static GUI_CONST_STORAGE unsigned char acGUI_Fontfont_size16_0038[ 12] = { /* code 0038, DIGIT EIGHT */
  __XXX___,
  _X___X__,
  X_____X_,
  X_____X_,
  _X___X__,
  __XXX___,
  _X___X__,
  X_____X_,
  X_____X_,
  X_____X_,
  _X___X__,
  __XXX___};

static GUI_CONST_STORAGE unsigned char acGUI_Fontfont_size16_0039[ 12] = { /* code 0039, DIGIT NINE */
  __XXX___,
  _X___X__,
  X_____X_,
  X_____X_,
  X_____X_,
  X_____X_,
  _X___XX_,
  __XXX_X_,
  ______X_,
  X_____X_,
  _X___X__,
  __XXX___};

static GUI_CONST_STORAGE unsigned char acGUI_Fontfont_size16_003A[  8] = { /* code 003A, COLON */
  X_______,
  X_______,
  ________,
  ________,
  ________,
  ________,
  X_______,
  X_______};

static GUI_CONST_STORAGE unsigned char acGUI_Fontfont_size16_003B[  9] = { /* code 003B, SEMICOLON */
  _X______,
  _X______,
  ________,
  ________,
  ________,
  ________,
  _X______,
  _X______,
  X_______};

static GUI_CONST_STORAGE unsigned char acGUI_Fontfont_size16_003C[ 13] = { /* code 003C, LESS-THAN SIGN */
  ______X_,
  _____X__,
  ____X___,
  ___X____,
  __X_____,
  _X______,
  X_______,
  _X______,
  __X_____,
  ___X____,
  ____X___,
  _____X__,
  ______X_};

static GUI_CONST_STORAGE unsigned char acGUI_Fontfont_size16_003D[  4] = { /* code 003D, EQUALS SIGN */
  XXXXXXX_,
  ________,
  ________,
  XXXXXXX_};

static GUI_CONST_STORAGE unsigned char acGUI_Fontfont_size16_003E[ 13] = { /* code 003E, GREATER-THAN SIGN */
  X_______,
  _X______,
  __X_____,
  ___X____,
  ____X___,
  _____X__,
  ______X_,
  _____X__,
  ____X___,
  ___X____,
  __X_____,
  _X______,
  X_______};

static GUI_CONST_STORAGE unsigned char acGUI_Fontfont_size16_003F[ 12] = { /* code 003F, QUESTION MARK */
  _XXXX___,
  X____X__,
  X____X__,
  _____X__,
  ____X___,
  ___X____,
  __X_____,
  __X_____,
  __X_____,
  ________,
  __X_____,
  __X_____};

static GUI_CONST_STORAGE unsigned char acGUI_Fontfont_size16_0040[ 26] = { /* code 0040, COMMERCIAL AT */
  _____XXX,XX______,
  ___XX___,__X_____,
  __X_____,___X____,
  _X___XXX,_X__X___,
  _X__X___,XX__X___,
  X__X____,_X__X___,
  X__X____,X___X___,
  X__X____,X___X___,
  X__X___X,X__X____,
  X___XXX_,_XX_____,
  _X______,________,
  __X_____,__X_____,
  ___XXXXX,XX______};

static GUI_CONST_STORAGE unsigned char acGUI_Fontfont_size16_0041[ 24] = { /* code 0041, LATIN CAPITAL LETTER A */
  ____X___,________,
  ____X___,________,
  ___X_X__,________,
  ___X_X__,________,
  __X___X_,________,
  __X___X_,________,
  _X_____X,________,
  _XXXXXXX,________,
  _X_____X,________,
  X_______,X_______,
  X_______,X_______,
  X_______,X_______};

static GUI_CONST_STORAGE unsigned char acGUI_Fontfont_size16_0042[ 12] = { /* code 0042, LATIN CAPITAL LETTER B */
  XXXXX___,
  X____X__,
  X_____X_,
  X_____X_,
  X____X__,
  XXXXXX__,
  X_____X_,
  X______X,
  X______X,
  X______X,
  X_____X_,
  XXXXXX__};

static GUI_CONST_STORAGE unsigned char acGUI_Fontfont_size16_0043[ 24] = { /* code 0043, LATIN CAPITAL LETTER C */
  ___XXXX_,________,
  __X____X,________,
  _X______,X_______,
  _X______,________,
  X_______,________,
  X_______,________,
  X_______,________,
  X_______,________,
  _X______,________,
  _X______,X_______,
  __X____X,________,
  ___XXXX_,________};

static GUI_CONST_STORAGE unsigned char acGUI_Fontfont_size16_0044[ 12] = { /* code 0044, LATIN CAPITAL LETTER D */
  XXXXX___,
  X____X__,
  X_____X_,
  X______X,
  X______X,
  X______X,
  X______X,
  X______X,
  X______X,
  X_____X_,
  X____X__,
  XXXXX___};

static GUI_CONST_STORAGE unsigned char acGUI_Fontfont_size16_0045[ 12] = { /* code 0045, LATIN CAPITAL LETTER E */
  XXXXXXXX,
  X_______,
  X_______,
  X_______,
  X_______,
  XXXXXXX_,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  XXXXXXXX};

static GUI_CONST_STORAGE unsigned char acGUI_Fontfont_size16_0046[ 12] = { /* code 0046, LATIN CAPITAL LETTER F */
  XXXXXXXX,
  X_______,
  X_______,
  X_______,
  X_______,
  XXXXXXX_,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______};

static GUI_CONST_STORAGE unsigned char acGUI_Fontfont_size16_0047[ 24] = { /* code 0047, LATIN CAPITAL LETTER G */
  ___XXXXX,________,
  __X_____,X_______,
  _X______,_X______,
  X_______,________,
  X_______,________,
  X_______,________,
  X____XXX,XX______,
  X_______,_X______,
  X_______,_X______,
  _X______,XX______,
  __X____X,_X______,
  ___XXXX_,_X______};

static GUI_CONST_STORAGE unsigned char acGUI_Fontfont_size16_0048[ 12] = { /* code 0048, LATIN CAPITAL LETTER H */
  X______X,
  X______X,
  X______X,
  X______X,
  X______X,
  XXXXXXXX,
  X______X,
  X______X,
  X______X,
  X______X,
  X______X,
  X______X};

static GUI_CONST_STORAGE unsigned char acGUI_Fontfont_size16_0049[ 12] = { /* code 0049, LATIN CAPITAL LETTER I */
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______};

static GUI_CONST_STORAGE unsigned char acGUI_Fontfont_size16_004A[ 12] = { /* code 004A, LATIN CAPITAL LETTER J */
  _____X__,
  _____X__,
  _____X__,
  _____X__,
  _____X__,
  _____X__,
  _____X__,
  _____X__,
  _____X__,
  X____X__,
  X____X__,
  _XXXX___};

static GUI_CONST_STORAGE unsigned char acGUI_Fontfont_size16_004B[ 24] = { /* code 004B, LATIN CAPITAL LETTER K */
  X______X,________,
  X_____X_,________,
  X____X__,________,
  X___X___,________,
  X__X____,________,
  X_X_____,________,
  XX_X____,________,
  X___X___,________,
  X____X__,________,
  X_____X_,________,
  X______X,________,
  X_______,X_______};

static GUI_CONST_STORAGE unsigned char acGUI_Fontfont_size16_004C[ 12] = { /* code 004C, LATIN CAPITAL LETTER L */
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  XXXXXXXX};

static GUI_CONST_STORAGE unsigned char acGUI_Fontfont_size16_004D[ 24] = { /* code 004D, LATIN CAPITAL LETTER M */
  X_______,__X_____,
  X_______,__X_____,
  XX______,_XX_____,
  XX______,_XX_____,
  X_X_____,X_X_____,
  X_X_____,X_X_____,
  X__X___X,__X_____,
  X__X___X,__X_____,
  X___X_X_,__X_____,
  X___X_X_,__X_____,
  X____X__,__X_____,
  X____X__,__X_____};

static GUI_CONST_STORAGE unsigned char acGUI_Fontfont_size16_004E[ 24] = { /* code 004E, LATIN CAPITAL LETTER N */
  X_______,X_______,
  XX______,X_______,
  XX______,X_______,
  X_X_____,X_______,
  X__X____,X_______,
  X__X____,X_______,
  X___X___,X_______,
  X____X__,X_______,
  X____X__,X_______,
  X_____X_,X_______,
  X______X,X_______,
  X______X,X_______};

static GUI_CONST_STORAGE unsigned char acGUI_Fontfont_size16_004F[ 24] = { /* code 004F, LATIN CAPITAL LETTER O */
  ___XXXX_,________,
  __X____X,________,
  _X______,X_______,
  X_______,_X______,
  X_______,_X______,
  X_______,_X______,
  X_______,_X______,
  X_______,_X______,
  X_______,_X______,
  _X______,X_______,
  __X____X,________,
  ___XXXX_,________};

static GUI_CONST_STORAGE unsigned char acGUI_Fontfont_size16_0050[ 12] = { /* code 0050, LATIN CAPITAL LETTER P */
  XXXXXX__,
  X_____X_,
  X______X,
  X______X,
  X______X,
  X_____X_,
  XXXXXX__,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______};

static GUI_CONST_STORAGE unsigned char acGUI_Fontfont_size16_0051[ 24] = { /* code 0051, LATIN CAPITAL LETTER Q */
  ___XXXX_,________,
  __X____X,________,
  _X______,X_______,
  X_______,_X______,
  X_______,_X______,
  X_______,_X______,
  X_______,_X______,
  X____X__,_X______,
  X_____X_,_X______,
  _X_____X,X_______,
  __X____X,X_______,
  ___XXXX_,_X______};

static GUI_CONST_STORAGE unsigned char acGUI_Fontfont_size16_0052[ 12] = { /* code 0052, LATIN CAPITAL LETTER R */
  XXXXXX__,
  X_____X_,
  X______X,
  X______X,
  X______X,
  X_____X_,
  XXXXXX__,
  X_____X_,
  X______X,
  X______X,
  X______X,
  X______X};

static GUI_CONST_STORAGE unsigned char acGUI_Fontfont_size16_0053[ 12] = { /* code 0053, LATIN CAPITAL LETTER S */
  __XXXX__,
  _X____X_,
  X______X,
  X_______,
  _X______,
  __XX____,
  ____XX__,
  ______X_,
  _______X,
  X______X,
  _X____X_,
  __XXXX__};

static GUI_CONST_STORAGE unsigned char acGUI_Fontfont_size16_0054[ 24] = { /* code 0054, LATIN CAPITAL LETTER T */
  XXXXXXXX,X_______,
  ____X___,________,
  ____X___,________,
  ____X___,________,
  ____X___,________,
  ____X___,________,
  ____X___,________,
  ____X___,________,
  ____X___,________,
  ____X___,________,
  ____X___,________,
  ____X___,________};

static GUI_CONST_STORAGE unsigned char acGUI_Fontfont_size16_0055[ 24] = { /* code 0055, LATIN CAPITAL LETTER U */
  X_______,X_______,
  X_______,X_______,
  X_______,X_______,
  X_______,X_______,
  X_______,X_______,
  X_______,X_______,
  X_______,X_______,
  X_______,X_______,
  X_______,X_______,
  X_______,X_______,
  _X_____X,________,
  __XXXXX_,________};

static GUI_CONST_STORAGE unsigned char acGUI_Fontfont_size16_0056[ 24] = { /* code 0056, LATIN CAPITAL LETTER V */
  X_______,X_______,
  X_______,X_______,
  _X_____X,________,
  _X_____X,________,
  _X_____X,________,
  __X___X_,________,
  __X___X_,________,
  __X___X_,________,
  ___X_X__,________,
  ___X_X__,________,
  ____X___,________,
  ____X___,________};

static GUI_CONST_STORAGE unsigned char acGUI_Fontfont_size16_0057[ 24] = { /* code 0057, LATIN CAPITAL LETTER W */
  X_____X_,____X___,
  X_____X_,____X___,
  X_____X_,____X___,
  _X___X_X,___X____,
  _X___X_X,___X____,
  _X___X_X,___X____,
  __X_X___,X_X_____,
  __X_X___,X_X_____,
  __X_X___,X_X_____,
  ___X____,_X______,
  ___X____,_X______,
  ___X____,_X______};

static GUI_CONST_STORAGE unsigned char acGUI_Fontfont_size16_0058[ 24] = { /* code 0058, LATIN CAPITAL LETTER X */
  X_______,X_______,
  X_______,X_______,
  _X_____X,________,
  __X___X_,________,
  ___X_X__,________,
  ____X___,________,
  ____X___,________,
  ___X_X__,________,
  __X___X_,________,
  _X_____X,________,
  X_______,X_______,
  X_______,X_______};

static GUI_CONST_STORAGE unsigned char acGUI_Fontfont_size16_0059[ 24] = { /* code 0059, LATIN CAPITAL LETTER Y */
  X_______,X_______,
  X_______,X_______,
  _X_____X,________,
  __X___X_,________,
  __X___X_,________,
  ___X_X__,________,
  ____X___,________,
  ____X___,________,
  ____X___,________,
  ____X___,________,
  ____X___,________,
  ____X___,________};

static GUI_CONST_STORAGE unsigned char acGUI_Fontfont_size16_005A[ 12] = { /* code 005A, LATIN CAPITAL LETTER Z */
  XXXXXXXX,
  _______X,
  ______X_,
  _____X__,
  _____X__,
  ____X___,
  ___X____,
  __X_____,
  __X_____,
  _X______,
  X_______,
  XXXXXXXX};

static GUI_CONST_STORAGE unsigned char acGUI_Fontfont_size16_005B[ 14] = { /* code 005B, LEFT SQUARE BRACKET */
  XXX_____,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  XXX_____};

static GUI_CONST_STORAGE unsigned char acGUI_Fontfont_size16_005C[ 24] = { /* code 005C, REVERSE SOLIDUS */
  X_____X_,____X___,
  X_____X_,____X___,
  X_____X_,____X___,
  _X___X_X,___X____,
  XXXXXXXX,XXXXX___,
  _X___X_X,___X____,
  __X_X___,X_X_____,
  __X_X___,X_X_____,
  __X_X___,X_X_____,
  ___X____,_X______,
  ___X____,_X______,
  ___X____,_X______};

static GUI_CONST_STORAGE unsigned char acGUI_Fontfont_size16_005D[ 14] = { /* code 005D, RIGHT SQUARE BRACKET */
  XXX_____,
  __X_____,
  __X_____,
  __X_____,
  __X_____,
  __X_____,
  __X_____,
  __X_____,
  __X_____,
  __X_____,
  __X_____,
  __X_____,
  __X_____,
  XXX_____};

static GUI_CONST_STORAGE unsigned char acGUI_Fontfont_size16_005E[  4] = { /* code 005E, CIRCUMFLEX ACCENT */
  ___X____,
  __X_X___,
  _X___X__,
  X_____X_};

static GUI_CONST_STORAGE unsigned char acGUI_Fontfont_size16_005F[  1] = { /* code 005F, LOW LINE */
  XXXXX___};

static GUI_CONST_STORAGE unsigned char acGUI_Fontfont_size16_0060[  3] = { /* code 0060, GRAVE ACCENT */
  X_______,
  _X______,
  __X_____};

static GUI_CONST_STORAGE unsigned char acGUI_Fontfont_size16_0061[  9] = { /* code 0061, LATIN SMALL LETTER A */
  _XXXXX__,
  X_____X_,
  ______X_,
  ___XXXX_,
  _XX___X_,
  X_____X_,
  X_____X_,
  X_____X_,
  _XXXXX_X};

static GUI_CONST_STORAGE unsigned char acGUI_Fontfont_size16_0062[ 12] = { /* code 0062, LATIN SMALL LETTER B */
  X_______,
  X_______,
  X_______,
  X_XXX___,
  XX___X__,
  X_____X_,
  X_____X_,
  X_____X_,
  X_____X_,
  X_____X_,
  XX___X__,
  X_XXX___};

static GUI_CONST_STORAGE unsigned char acGUI_Fontfont_size16_0063[  9] = { /* code 0063, LATIN SMALL LETTER C */
  __XXXX__,
  _X____X_,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  _X____X_,
  __XXXX__};

static GUI_CONST_STORAGE unsigned char acGUI_Fontfont_size16_0064[ 12] = { /* code 0064, LATIN SMALL LETTER D */
  ______X_,
  ______X_,
  ______X_,
  __XXX_X_,
  _X___XX_,
  X_____X_,
  X_____X_,
  X_____X_,
  X_____X_,
  X_____X_,
  _X___XX_,
  __XXX_X_};

static GUI_CONST_STORAGE unsigned char acGUI_Fontfont_size16_0065[  9] = { /* code 0065, LATIN SMALL LETTER E */
  __XXX___,
  _X___X__,
  X_____X_,
  X_____X_,
  XXXXXXX_,
  X_______,
  X_______,
  _X____X_,
  __XXXX__};

static GUI_CONST_STORAGE unsigned char acGUI_Fontfont_size16_0066[ 12] = { /* code 0066, LATIN SMALL LETTER F */
  ___XX___,
  __X_____,
  __X_____,
  XXXXX___,
  __X_____,
  __X_____,
  __X_____,
  __X_____,
  __X_____,
  __X_____,
  __X_____,
  __X_____};

static GUI_CONST_STORAGE unsigned char acGUI_Fontfont_size16_0067[ 11] = { /* code 0067, LATIN SMALL LETTER G */
  __XXX_X_,
  _X___XX_,
  X_____X_,
  X_____X_,
  X_____X_,
  X_____X_,
  _X___XX_,
  __XXX_X_,
  ______X_,
  X____X__,
  _XXXX___};

static GUI_CONST_STORAGE unsigned char acGUI_Fontfont_size16_0068[ 12] = { /* code 0068, LATIN SMALL LETTER H */
  X_______,
  X_______,
  X_______,
  X_XXXX__,
  XX____X_,
  X_____X_,
  X_____X_,
  X_____X_,
  X_____X_,
  X_____X_,
  X_____X_,
  X_____X_};

static GUI_CONST_STORAGE unsigned char acGUI_Fontfont_size16_0069[ 12] = { /* code 0069, LATIN SMALL LETTER I */
  X_______,
  X_______,
  ________,
  ________,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______};

static GUI_CONST_STORAGE unsigned char acGUI_Fontfont_size16_006A[ 14] = { /* code 006A, LATIN SMALL LETTER J */
  __X_____,
  __X_____,
  ________,
  ________,
  __X_____,
  __X_____,
  __X_____,
  __X_____,
  __X_____,
  __X_____,
  __X_____,
  __X_____,
  __X_____,
  XX______};

static GUI_CONST_STORAGE unsigned char acGUI_Fontfont_size16_006B[ 12] = { /* code 006B, LATIN SMALL LETTER K */
  X_______,
  X_______,
  X_______,
  X____X__,
  X___X___,
  X__X____,
  X_X_____,
  XXX_____,
  X__X____,
  X___X___,
  X____X__,
  X_____X_};

static GUI_CONST_STORAGE unsigned char acGUI_Fontfont_size16_006C[ 12] = { /* code 006C, LATIN SMALL LETTER L */
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______};

static GUI_CONST_STORAGE unsigned char acGUI_Fontfont_size16_006D[ 18] = { /* code 006D, LATIN SMALL LETTER M */
  X_XXX__X,XX______,
  XX___XX_,__X_____,
  X____X__,__X_____,
  X____X__,__X_____,
  X____X__,__X_____,
  X____X__,__X_____,
  X____X__,__X_____,
  X____X__,__X_____,
  X____X__,__X_____};

static GUI_CONST_STORAGE unsigned char acGUI_Fontfont_size16_006E[  9] = { /* code 006E, LATIN SMALL LETTER N */
  X_XXXX__,
  XX____X_,
  X_____X_,
  X_____X_,
  X_____X_,
  X_____X_,
  X_____X_,
  X_____X_,
  X_____X_};

static GUI_CONST_STORAGE unsigned char acGUI_Fontfont_size16_006F[  9] = { /* code 006F, LATIN SMALL LETTER O */
  __XXXX__,
  _X____X_,
  X______X,
  X______X,
  X______X,
  X______X,
  X______X,
  _X____X_,
  __XXXX__};

static GUI_CONST_STORAGE unsigned char acGUI_Fontfont_size16_0070[ 11] = { /* code 0070, LATIN SMALL LETTER P */
  X_XXX___,
  XX___X__,
  X_____X_,
  X_____X_,
  X_____X_,
  X_____X_,
  X_____X_,
  XX___X__,
  X_XXX___,
  X_______,
  X_______};

static GUI_CONST_STORAGE unsigned char acGUI_Fontfont_size16_0071[ 11] = { /* code 0071, LATIN SMALL LETTER Q */
  __XXX_X_,
  _X___XX_,
  X_____X_,
  X_____X_,
  X_____X_,
  X_____X_,
  X_____X_,
  _X___XX_,
  __XXX_X_,
  ______X_,
  ______X_};

static GUI_CONST_STORAGE unsigned char acGUI_Fontfont_size16_0072[  9] = { /* code 0072, LATIN SMALL LETTER R */
  X_XX____,
  XX______,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______};

static GUI_CONST_STORAGE unsigned char acGUI_Fontfont_size16_0073[  9] = { /* code 0073, LATIN SMALL LETTER S */
  _XXXXX__,
  X_____X_,
  X_______,
  _XX_____,
  ___XX___,
  _____X__,
  ______X_,
  X_____X_,
  _XXXXX__};

static GUI_CONST_STORAGE unsigned char acGUI_Fontfont_size16_0074[ 12] = { /* code 0074, LATIN SMALL LETTER T */
  __X_____,
  __X_____,
  __X_____,
  XXXXX___,
  __X_____,
  __X_____,
  __X_____,
  __X_____,
  __X_____,
  __X_____,
  __X_____,
  ___XX___};

static GUI_CONST_STORAGE unsigned char acGUI_Fontfont_size16_0075[  9] = { /* code 0075, LATIN SMALL LETTER U */
  X_____X_,
  X_____X_,
  X_____X_,
  X_____X_,
  X_____X_,
  X_____X_,
  X_____X_,
  X____XX_,
  _XXXX_X_};

static GUI_CONST_STORAGE unsigned char acGUI_Fontfont_size16_0076[  9] = { /* code 0076, LATIN SMALL LETTER V */
  X_____X_,
  X_____X_,
  X_____X_,
  _X___X__,
  _X___X__,
  __X_X___,
  __X_X___,
  ___X____,
  ___X____};

static GUI_CONST_STORAGE unsigned char acGUI_Fontfont_size16_0077[ 18] = { /* code 0077, LATIN SMALL LETTER W */
  X____X__,__X_____,
  X____X__,__X_____,
  X____X__,__X_____,
  _X__X_X_,_X______,
  _X__X_X_,_X______,
  _X_X___X,_X______,
  __XX___X,X_______,
  __X_____,X_______,
  __X_____,X_______};

static GUI_CONST_STORAGE unsigned char acGUI_Fontfont_size16_0078[  9] = { /* code 0078, LATIN SMALL LETTER X */
  X_____X_,
  X_____X_,
  _X___X__,
  __X_X___,
  ___X____,
  __X_X___,
  _X___X__,
  X_____X_,
  X_____X_};

static GUI_CONST_STORAGE unsigned char acGUI_Fontfont_size16_0079[ 11] = { /* code 0079, LATIN SMALL LETTER Y */
  X_____X_,
  X_____X_,
  X_____X_,
  _X___X__,
  _X___X__,
  __X_X___,
  __X_X___,
  ___X____,
  ___X____,
  __X_____,
  XX______};

static GUI_CONST_STORAGE unsigned char acGUI_Fontfont_size16_007A[  9] = { /* code 007A, LATIN SMALL LETTER Z */
  XXXXXXX_,
  ______X_,
  _____X__,
  ____X___,
  ___X____,
  __X_____,
  _X______,
  X_______,
  XXXXXXX_};

static GUI_CONST_STORAGE unsigned char acGUI_Fontfont_size16_007B[ 14] = { /* code 007B, LEFT CURLY BRACKET */
  ___XX___,
  __X_____,
  __X_____,
  __X_____,
  __X_____,
  __X_____,
  XX______,
  __X_____,
  __X_____,
  __X_____,
  __X_____,
  __X_____,
  __X_____,
  ___XX___};

static GUI_CONST_STORAGE unsigned char acGUI_Fontfont_size16_007C[ 14] = { /* code 007C, VERTICAL LINE */
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______};

static GUI_CONST_STORAGE unsigned char acGUI_Fontfont_size16_007D[ 14] = { /* code 007D, RIGHT CURLY BRACKET */
  XX______,
  __X_____,
  __X_____,
  __X_____,
  __X_____,
  __X_____,
  ___XX___,
  __X_____,
  __X_____,
  __X_____,
  __X_____,
  __X_____,
  __X_____,
  XX______};

static GUI_CONST_STORAGE unsigned char acGUI_Fontfont_size16_007E[  4] = { /* code 007E, TILDE */
  _XXXX___,_X______,
  X____XXX,X_______};

static GUI_CONST_STORAGE unsigned char acGUI_Fontfont_size16_007F[ 11] = { /* code 007F, <control> */
  XXXXXX__,
  X____X__,
  X____X__,
  X____X__,
  X____X__,
  X____X__,
  X____X__,
  X____X__,
  X____X__,
  X____X__,
  XXXXXX__};

/* Start of unicode area <Hangul Syllables> */
static GUI_CONST_STORAGE unsigned char acGUI_Fontfont_size16_ACC4[ 32] = { /* code ACC4 */
  ________,_____X__,
  ________,__X__X__,
  __XXXXXX,__X__X__,
  _______X,__X__X__,
  _______X,XXX__X__,
  _______X,__X__X__,
  ______X_,__X__X__,
  ______X_,__X__X__,
  _____X_X,XXX__X__,
  ____X___,__X__X__,
  ___X____,__X__X__,
  _XX_____,__X__X__,
  ________,__X__X__,
  ________,__X__X__,
  ________,_____X__,
  ________,________};

static GUI_CONST_STORAGE unsigned char acGUI_Fontfont_size16_B839[ 32] = { /* code B839 */
  ________,____X___,
  __XXXXXX,____X___,
  _______X,_XXXX___,
  _______X,____X___,
  __XXXXXX,____X___,
  __X_____,_XXXX___,
  __X_____,____X___,
  __X_____,____X___,
  __XXXXXX,____X___,
  ________,________,
  _____XXX,XXXX____,
  ____X___,____X___,
  ____X___,____X___,
  ____X___,____X___,
  _____XXX,XXXX____,
  ________,________};

static GUI_CONST_STORAGE unsigned char acGUI_Fontfont_size16_BA85[ 32] = { /* code BA85 */
  ________,____X___,
  __XXXXXX,X___X___,
  __X_____,XXXXX___,
  __X_____,X___X___,
  __X_____,X___X___,
  __X_____,XXXXX___,
  __X_____,X___X___,
  __XXXXXX,X___X___,
  ________,____X___,
  ______XX,XXX_____,
  _____X__,___X____,
  ____X___,____X___,
  ____X___,____X___,
  _____X__,___X____,
  ______XX,XXX_____,
  ________,________};

static GUI_CONST_STORAGE unsigned char acGUI_Fontfont_size16_BCA4[ 32] = { /* code BCA4 */
  ________,__X__X__,
  __X____X,__X__X__,
  __X____X,__X__X__,
  __X____X,__X__X__,
  __XXXXXX,XXX__X__,
  __X____X,__X__X__,
  __X____X,__X__X__,
  __X____X,__X__X__,
  __XXXXXX,__X__X__,
  ________,__X__X__,
  ________,_____X__,
  ____X___,________,
  ____X___,________,
  ____X___,________,
  ____XXXX,XXXXXX__,
  ________,________};

static GUI_CONST_STORAGE unsigned char acGUI_Fontfont_size16_BCF4[ 32] = { /* code BCF4 */
  ________,________,
  ________,________,
  ___X____,____X___,
  ___X____,____X___,
  ___XXXXX,XXXXX___,
  ___X____,____X___,
  ___X____,____X___,
  ___X____,____X___,
  ___XXXXX,XXXXX___,
  ________,X_______,
  ________,X_______,
  ________,X_______,
  ________,X_______,
  _XXXXXXX,XXXXXXX_,
  ________,________,
  ________,________};

static GUI_CONST_STORAGE unsigned char acGUI_Fontfont_size16_C0C1[ 32] = { /* code C0C1 */
  ________,____X___,
  _____X__,____X___,
  _____X__,____X___,
  _____X__,____X___,
  ____X_X_,____XXXX,
  ____X__X,____X___,
  ___X____,X___X___,
  __X_____,_X__X___,
  _X______,____X___,
  ______XX,XXX_____,
  _____X__,___X____,
  ____X___,____X___,
  ____X___,____X___,
  _____X__,___X____,
  ______XX,XXX_____,
  ________,________};

static GUI_CONST_STORAGE unsigned char acGUI_Fontfont_size16_C124[ 32] = { /* code C124 */
  ________,____X___,
  _____X__,____X___,
  _____X__,____X___,
  _____X__,XXXXX___,
  ____X_X_,____X___,
  ____X__X,____X___,
  ___X____,X___X___,
  __X_____,_X__X___,
  _X______,________,
  ___XXXXX,XXXXX___,
  ________,____X___,
  ___XXXXX,XXXXX___,
  ___X____,________,
  ___X____,________,
  ___XXXXX,XXXXX___,
  ________,________};

static GUI_CONST_STORAGE unsigned char acGUI_Fontfont_size16_C2A4[ 32] = { /* code C2A4 */
  ________,________,
  ________,________,
  ________,X_______,
  ________,X_______,
  ________,X_______,
  _______X,_X______,
  ______X_,__X_____,
  ____XX__,___XX___,
  __XX____,_____XX_,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  _XXXXXXX,XXXXXXX_,
  ________,________,
  ________,________};

static GUI_CONST_STORAGE unsigned char acGUI_Fontfont_size16_C2DC[ 32] = { /* code C2DC */
  ________,____X___,
  _____X__,____X___,
  _____X__,____X___,
  _____X__,____X___,
  _____X__,____X___,
  _____X__,____X___,
  _____X__,____X___,
  ____X_X_,____X___,
  ____X_X_,____X___,
  ___X___X,____X___,
  __X_____,X___X___,
  _X______,_X__X___,
  ________,____X___,
  ________,____X___,
  ________,____X___,
  ________,________};

static GUI_CONST_STORAGE unsigned char acGUI_Fontfont_size16_C774[ 32] = { /* code C774 */
  ________,____X___,
  ________,____X___,
  ____XXX_,____X___,
  ___X___X,____X___,
  __X_____,X___X___,
  __X_____,X___X___,
  __X_____,X___X___,
  __X_____,X___X___,
  __X_____,X___X___,
  __X_____,X___X___,
  ___X___X,____X___,
  ____XXX_,____X___,
  ________,____X___,
  ________,____X___,
  ________,____X___,
  ________,________};

static GUI_CONST_STORAGE unsigned char acGUI_Fontfont_size16_C815[ 32] = { /* code C815 */
  ________,____X___,
  _XXXXXXX,XX__X___,
  _____X__,____X___,
  _____X__,____X___,
  ____X_X_,_XXXX___,
  ____X__X,____X___,
  ___X____,X___X___,
  __X_____,_X__X___,
  _X______,____X___,
  ______XX,XXX_____,
  _____X__,___X____,
  ____X___,____X___,
  ____X___,____X___,
  _____X__,___X____,
  ______XX,XXX_____,
  ________,________};

static GUI_CONST_STORAGE unsigned char acGUI_Fontfont_size16_CE21[ 32] = { /* code CE21 */
  ______XX,XX______,
  ________,________,
  ___XXXXX,XXXXX___,
  ________,X_______,
  ______XX,_XX_____,
  __XXXX__,___XXX__,
  ________,________,
  ________,________,
  _XXXXXXX,XXXXXXX_,
  ________,________,
  ________,________,
  ___XXXXX,XXXXX___,
  ________,____X___,
  ________,____X___,
  ________,____X___,
  ________,________};

static GUI_CONST_STORAGE unsigned char acGUI_Fontfont_size16_D0DC[ 32] = { /* code D0DC */
  ________,_____X__,
  ________,__X__X__,
  __XXXXXX,__X__X__,
  __X_____,__X__X__,
  __X_____,__X__X__,
  __X_____,__X__X__,
  __XXXXXX,__XXXX__,
  __X_____,__X__X__,
  __X_____,__X__X__,
  __X_____,__X__X__,
  __X_____,__X__X__,
  __XXXXXX,X_X__X__,
  ________,__X__X__,
  ________,__X__X__,
  ________,_____X__,
  ________,________};

static GUI_CONST_STORAGE unsigned char acGUI_Fontfont_size16_D15C[ 32] = { /* code D15C */
  ________,__X__X__,
  __XXXXX_,__X__X__,
  __X_____,__X__X__,
  __X_____,__X__X__,
  __XXXXX_,XXX__X__,
  __X_____,__X__X__,
  __X_____,__X__X__,
  __XXXXXX,__X__X__,
  ________,_____X__,
  ________,________,
  ____XXXX,XXXXXX__,
  ____X___,_____X__,
  ____X___,_____X__,
  ____X___,_____X__,
  ____XXXX,XXXXXX__,
  ________,________};

static GUI_CONST_STORAGE unsigned char acGUI_Fontfont_size16_D2B8[ 32] = { /* code D2B8 */
  ________,________,
  ________,________,
  ___XXXXX,XXXXX___,
  ___X____,________,
  ___X____,________,
  ___XXXXX,XXXXX___,
  ___X____,________,
  ___X____,________,
  ___X____,________,
  ___XXXXX,XXXXX___,
  ________,________,
  ________,________,
  ________,________,
  _XXXXXXX,XXXXXXX_,
  ________,________,
  ________,________};

static GUI_CONST_STORAGE unsigned char acGUI_Fontfont_size16_D638[ 32] = { /* code D638 */
  ________,________,
  _____XXX,XXX_____,
  ________,________,
  __XXXXXX,XXXXXX__,
  ________,________,
  _____XXX,XXX_____,
  ____X___,___X____,
  ____X___,___X____,
  ____X___,___X____,
  _____XXX,XXX_____,
  ________,X_______,
  ________,X_______,
  ________,X_______,
  _XXXXXXX,XXXXXXX_,
  ________,________,
  ________,________};

static GUI_CONST_STORAGE GUI_CHARINFO_EXT GUI_Fontfont_size16_CharInfo[103] = {
   {   7,  14,   1,   1,   8, acGUI_Fontfont_size16_001E } /* code 001E, <control> */
  ,{   7,  14,   1,   1,   8, acGUI_Fontfont_size16_001F } /* code 001F, <control> */
  ,{   1,   1,   0,  14,   5, acGUI_Fontfont_size16_0020 } /* code 0020, SPACE */
  ,{   5,   5,   1,   5,   7, acGUI_Fontfont_size16_002A } /* code 002A, ASTERISK */
  ,{   7,   7,   1,   4,   8, acGUI_Fontfont_size16_002B } /* code 002B, PLUS SIGN */
  ,{   7,   1,   1,   7,   8, acGUI_Fontfont_size16_002D } /* code 002D, HYPHEN-MINUS */
  ,{   1,   2,   2,  12,   5, acGUI_Fontfont_size16_002E } /* code 002E, FULL STOP */
  ,{   7,  12,   1,   2,   8, acGUI_Fontfont_size16_0030 } /* code 0030, DIGIT ZERO */
  ,{   3,  12,   2,   2,   8, acGUI_Fontfont_size16_0031 } /* code 0031, DIGIT ONE */
  ,{   7,  12,   1,   2,   8, acGUI_Fontfont_size16_0032 } /* code 0032, DIGIT TWO */
  ,{   7,  12,   1,   2,   8, acGUI_Fontfont_size16_0033 } /* code 0033, DIGIT THREE */
  ,{   8,  12,   0,   2,   8, acGUI_Fontfont_size16_0034 } /* code 0034, DIGIT FOUR */
  ,{   8,  12,   0,   2,   8, acGUI_Fontfont_size16_0035 } /* code 0035, DIGIT FIVE */
  ,{   7,  12,   1,   2,   8, acGUI_Fontfont_size16_0036 } /* code 0036, DIGIT SIX */
  ,{   7,  12,   1,   2,   8, acGUI_Fontfont_size16_0037 } /* code 0037, DIGIT SEVEN */
  ,{   7,  12,   1,   2,   8, acGUI_Fontfont_size16_0038 } /* code 0038, DIGIT EIGHT */
  ,{   7,  12,   1,   2,   8, acGUI_Fontfont_size16_0039 } /* code 0039, DIGIT NINE */
  ,{   1,   8,   2,   4,   5, acGUI_Fontfont_size16_003A } /* code 003A, COLON */
  ,{   2,   9,   1,   4,   5, acGUI_Fontfont_size16_003B } /* code 003B, SEMICOLON */
  ,{   7,  13,   1,   1,   9, acGUI_Fontfont_size16_003C } /* code 003C, LESS-THAN SIGN */
  ,{   7,   4,   1,   6,   8, acGUI_Fontfont_size16_003D } /* code 003D, EQUALS SIGN */
  ,{   7,  13,   1,   1,   9, acGUI_Fontfont_size16_003E } /* code 003E, GREATER-THAN SIGN */
  ,{   6,  12,   1,   2,   8, acGUI_Fontfont_size16_003F } /* code 003F, QUESTION MARK */
  ,{  13,  13,   2,   1,  16, acGUI_Fontfont_size16_0040 } /* code 0040, COMMERCIAL AT */
  ,{   9,  12,   1,   2,  10, acGUI_Fontfont_size16_0041 } /* code 0041, LATIN CAPITAL LETTER A */
  ,{   8,  12,   1,   2,  10, acGUI_Fontfont_size16_0042 } /* code 0042, LATIN CAPITAL LETTER B */
  ,{   9,  12,   1,   2,  11, acGUI_Fontfont_size16_0043 } /* code 0043, LATIN CAPITAL LETTER C */
  ,{   8,  12,   1,   2,  10, acGUI_Fontfont_size16_0044 } /* code 0044, LATIN CAPITAL LETTER D */
  ,{   8,  12,   1,   2,  10, acGUI_Fontfont_size16_0045 } /* code 0045, LATIN CAPITAL LETTER E */
  ,{   8,  12,   1,   2,   9, acGUI_Fontfont_size16_0046 } /* code 0046, LATIN CAPITAL LETTER F */
  ,{  10,  12,   1,   2,  12, acGUI_Fontfont_size16_0047 } /* code 0047, LATIN CAPITAL LETTER G */
  ,{   8,  12,   1,   2,  10, acGUI_Fontfont_size16_0048 } /* code 0048, LATIN CAPITAL LETTER H */
  ,{   1,  12,   1,   2,   3, acGUI_Fontfont_size16_0049 } /* code 0049, LATIN CAPITAL LETTER I */
  ,{   6,  12,   1,   2,   8, acGUI_Fontfont_size16_004A } /* code 004A, LATIN CAPITAL LETTER J */
  ,{   9,  12,   1,   2,  10, acGUI_Fontfont_size16_004B } /* code 004B, LATIN CAPITAL LETTER K */
  ,{   8,  12,   1,   2,   9, acGUI_Fontfont_size16_004C } /* code 004C, LATIN CAPITAL LETTER L */
  ,{  11,  12,   1,   2,  13, acGUI_Fontfont_size16_004D } /* code 004D, LATIN CAPITAL LETTER M */
  ,{   9,  12,   1,   2,  11, acGUI_Fontfont_size16_004E } /* code 004E, LATIN CAPITAL LETTER N */
  ,{  10,  12,   1,   2,  12, acGUI_Fontfont_size16_004F } /* code 004F, LATIN CAPITAL LETTER O */
  ,{   8,  12,   1,   2,  10, acGUI_Fontfont_size16_0050 } /* code 0050, LATIN CAPITAL LETTER P */
  ,{  10,  12,   1,   2,  12, acGUI_Fontfont_size16_0051 } /* code 0051, LATIN CAPITAL LETTER Q */
  ,{   8,  12,   1,   2,  10, acGUI_Fontfont_size16_0052 } /* code 0052, LATIN CAPITAL LETTER R */
  ,{   8,  12,   1,   2,  10, acGUI_Fontfont_size16_0053 } /* code 0053, LATIN CAPITAL LETTER S */
  ,{   9,  12,   0,   2,   9, acGUI_Fontfont_size16_0054 } /* code 0054, LATIN CAPITAL LETTER T */
  ,{   9,  12,   1,   2,  11, acGUI_Fontfont_size16_0055 } /* code 0055, LATIN CAPITAL LETTER U */
  ,{   9,  12,   1,   2,  10, acGUI_Fontfont_size16_0056 } /* code 0056, LATIN CAPITAL LETTER V */
  ,{  13,  12,   1,   2,  14, acGUI_Fontfont_size16_0057 } /* code 0057, LATIN CAPITAL LETTER W */
  ,{   9,  12,   1,   2,  11, acGUI_Fontfont_size16_0058 } /* code 0058, LATIN CAPITAL LETTER X */
  ,{   9,  12,   1,   2,  10, acGUI_Fontfont_size16_0059 } /* code 0059, LATIN CAPITAL LETTER Y */
  ,{   8,  12,   1,   2,  10, acGUI_Fontfont_size16_005A } /* code 005A, LATIN CAPITAL LETTER Z */
  ,{   3,  14,   3,   1,   8, acGUI_Fontfont_size16_005B } /* code 005B, LEFT SQUARE BRACKET */
  ,{  13,  12,   1,   2,  14, acGUI_Fontfont_size16_005C } /* code 005C, REVERSE SOLIDUS */
  ,{   3,  14,   2,   1,   8, acGUI_Fontfont_size16_005D } /* code 005D, RIGHT SQUARE BRACKET */
  ,{   7,   4,   1,   1,   8, acGUI_Fontfont_size16_005E } /* code 005E, CIRCUMFLEX ACCENT */
  ,{   5,   1,   1,  13,   6, acGUI_Fontfont_size16_005F } /* code 005F, LOW LINE */
  ,{   3,   3,   1,   1,   5, acGUI_Fontfont_size16_0060 } /* code 0060, GRAVE ACCENT */
  ,{   8,   9,   1,   5,   9, acGUI_Fontfont_size16_0061 } /* code 0061, LATIN SMALL LETTER A */
  ,{   7,  12,   1,   2,   9, acGUI_Fontfont_size16_0062 } /* code 0062, LATIN SMALL LETTER B */
  ,{   7,   9,   1,   5,   9, acGUI_Fontfont_size16_0063 } /* code 0063, LATIN SMALL LETTER C */
  ,{   7,  12,   1,   2,   9, acGUI_Fontfont_size16_0064 } /* code 0064, LATIN SMALL LETTER D */
  ,{   7,   9,   1,   5,   9, acGUI_Fontfont_size16_0065 } /* code 0065, LATIN SMALL LETTER E */
  ,{   5,  12,   0,   2,   5, acGUI_Fontfont_size16_0066 } /* code 0066, LATIN SMALL LETTER F */
  ,{   7,  11,   1,   5,   9, acGUI_Fontfont_size16_0067 } /* code 0067, LATIN SMALL LETTER G */
  ,{   7,  12,   1,   2,   9, acGUI_Fontfont_size16_0068 } /* code 0068, LATIN SMALL LETTER H */
  ,{   1,  12,   1,   2,   3, acGUI_Fontfont_size16_0069 } /* code 0069, LATIN SMALL LETTER I */
  ,{   3,  14,   0,   2,   4, acGUI_Fontfont_size16_006A } /* code 006A, LATIN SMALL LETTER J */
  ,{   7,  12,   1,   2,   8, acGUI_Fontfont_size16_006B } /* code 006B, LATIN SMALL LETTER K */
  ,{   1,  12,   1,   2,   3, acGUI_Fontfont_size16_006C } /* code 006C, LATIN SMALL LETTER L */
  ,{  11,   9,   1,   5,  13, acGUI_Fontfont_size16_006D } /* code 006D, LATIN SMALL LETTER M */
  ,{   7,   9,   1,   5,   9, acGUI_Fontfont_size16_006E } /* code 006E, LATIN SMALL LETTER N */
  ,{   8,   9,   1,   5,  10, acGUI_Fontfont_size16_006F } /* code 006F, LATIN SMALL LETTER O */
  ,{   7,  11,   1,   5,   9, acGUI_Fontfont_size16_0070 } /* code 0070, LATIN SMALL LETTER P */
  ,{   7,  11,   1,   5,   9, acGUI_Fontfont_size16_0071 } /* code 0071, LATIN SMALL LETTER Q */
  ,{   4,   9,   1,   5,   5, acGUI_Fontfont_size16_0072 } /* code 0072, LATIN SMALL LETTER R */
  ,{   7,   9,   1,   5,   9, acGUI_Fontfont_size16_0073 } /* code 0073, LATIN SMALL LETTER S */
  ,{   5,  12,   0,   2,   5, acGUI_Fontfont_size16_0074 } /* code 0074, LATIN SMALL LETTER T */
  ,{   7,   9,   1,   5,   9, acGUI_Fontfont_size16_0075 } /* code 0075, LATIN SMALL LETTER U */
  ,{   7,   9,   1,   5,   8, acGUI_Fontfont_size16_0076 } /* code 0076, LATIN SMALL LETTER V */
  ,{  11,   9,   1,   5,  12, acGUI_Fontfont_size16_0077 } /* code 0077, LATIN SMALL LETTER W */
  ,{   7,   9,   1,   5,   9, acGUI_Fontfont_size16_0078 } /* code 0078, LATIN SMALL LETTER X */
  ,{   7,  11,   1,   5,   8, acGUI_Fontfont_size16_0079 } /* code 0079, LATIN SMALL LETTER Y */
  ,{   7,   9,   1,   5,   9, acGUI_Fontfont_size16_007A } /* code 007A, LATIN SMALL LETTER Z */
  ,{   5,  14,   2,   1,   9, acGUI_Fontfont_size16_007B } /* code 007B, LEFT CURLY BRACKET */
  ,{   1,  14,   4,   1,   9, acGUI_Fontfont_size16_007C } /* code 007C, VERTICAL LINE */
  ,{   5,  14,   2,   1,   9, acGUI_Fontfont_size16_007D } /* code 007D, RIGHT CURLY BRACKET */
  ,{  10,   2,   1,   7,  12, acGUI_Fontfont_size16_007E } /* code 007E, TILDE */
  ,{   6,  11,   1,   3,   8, acGUI_Fontfont_size16_007F } /* code 007F, <control> */
  ,{  16,  16,   0,   0,  16, acGUI_Fontfont_size16_ACC4 } /* code ACC4 */
  ,{  16,  16,   0,   0,  16, acGUI_Fontfont_size16_B839 } /* code B839 */
  ,{  16,  16,   0,   0,  16, acGUI_Fontfont_size16_BA85 } /* code BA85 */
  ,{  16,  16,   0,   0,  16, acGUI_Fontfont_size16_BCA4 } /* code BCA4 */
  ,{  16,  16,   0,   0,  16, acGUI_Fontfont_size16_BCF4 } /* code BCF4 */
  ,{  16,  16,   0,   0,  16, acGUI_Fontfont_size16_C0C1 } /* code C0C1 */
  ,{  16,  16,   0,   0,  16, acGUI_Fontfont_size16_C124 } /* code C124 */
  ,{  16,  16,   0,   0,  16, acGUI_Fontfont_size16_C2A4 } /* code C2A4 */
  ,{  16,  16,   0,   0,  16, acGUI_Fontfont_size16_C2DC } /* code C2DC */
  ,{  16,  16,   0,   0,  16, acGUI_Fontfont_size16_C774 } /* code C774 */
  ,{  16,  16,   0,   0,  16, acGUI_Fontfont_size16_C815 } /* code C815 */
  ,{  16,  16,   0,   0,  16, acGUI_Fontfont_size16_CE21 } /* code CE21 */
  ,{  16,  16,   0,   0,  16, acGUI_Fontfont_size16_D0DC } /* code D0DC */
  ,{  16,  16,   0,   0,  16, acGUI_Fontfont_size16_D15C } /* code D15C */
  ,{  16,  16,   0,   0,  16, acGUI_Fontfont_size16_D2B8 } /* code D2B8 */
  ,{  16,  16,   0,   0,  16, acGUI_Fontfont_size16_D638 } /* code D638 */
};

static GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_Fontfont_size16_Prop20 = {
   0xD638 /* first character */
  ,0xD638 /* last character  */
  ,&GUI_Fontfont_size16_CharInfo[102] /* address of first character */
  ,(GUI_CONST_STORAGE GUI_FONT_PROP_EXT *)0 /* pointer to next GUI_FONT_PROP_EXT */
};

static GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_Fontfont_size16_Prop19 = {
   0xD2B8 /* first character */
  ,0xD2B8 /* last character  */
  ,&GUI_Fontfont_size16_CharInfo[101] /* address of first character */
  ,&GUI_Fontfont_size16_Prop20 /* pointer to next GUI_FONT_PROP_EXT */
};

static GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_Fontfont_size16_Prop18 = {
   0xD15C /* first character */
  ,0xD15C /* last character  */
  ,&GUI_Fontfont_size16_CharInfo[100] /* address of first character */
  ,&GUI_Fontfont_size16_Prop19 /* pointer to next GUI_FONT_PROP_EXT */
};

static GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_Fontfont_size16_Prop17 = {
   0xD0DC /* first character */
  ,0xD0DC /* last character  */
  ,&GUI_Fontfont_size16_CharInfo[ 99] /* address of first character */
  ,&GUI_Fontfont_size16_Prop18 /* pointer to next GUI_FONT_PROP_EXT */
};

static GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_Fontfont_size16_Prop16 = {
   0xCE21 /* first character */
  ,0xCE21 /* last character  */
  ,&GUI_Fontfont_size16_CharInfo[ 98] /* address of first character */
  ,&GUI_Fontfont_size16_Prop17 /* pointer to next GUI_FONT_PROP_EXT */
};

static GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_Fontfont_size16_Prop15 = {
   0xC815 /* first character */
  ,0xC815 /* last character  */
  ,&GUI_Fontfont_size16_CharInfo[ 97] /* address of first character */
  ,&GUI_Fontfont_size16_Prop16 /* pointer to next GUI_FONT_PROP_EXT */
};

static GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_Fontfont_size16_Prop14 = {
   0xC774 /* first character */
  ,0xC774 /* last character  */
  ,&GUI_Fontfont_size16_CharInfo[ 96] /* address of first character */
  ,&GUI_Fontfont_size16_Prop15 /* pointer to next GUI_FONT_PROP_EXT */
};

static GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_Fontfont_size16_Prop13 = {
   0xC2DC /* first character */
  ,0xC2DC /* last character  */
  ,&GUI_Fontfont_size16_CharInfo[ 95] /* address of first character */
  ,&GUI_Fontfont_size16_Prop14 /* pointer to next GUI_FONT_PROP_EXT */
};

static GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_Fontfont_size16_Prop12 = {
   0xC2A4 /* first character */
  ,0xC2A4 /* last character  */
  ,&GUI_Fontfont_size16_CharInfo[ 94] /* address of first character */
  ,&GUI_Fontfont_size16_Prop13 /* pointer to next GUI_FONT_PROP_EXT */
};

static GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_Fontfont_size16_Prop11 = {
   0xC124 /* first character */
  ,0xC124 /* last character  */
  ,&GUI_Fontfont_size16_CharInfo[ 93] /* address of first character */
  ,&GUI_Fontfont_size16_Prop12 /* pointer to next GUI_FONT_PROP_EXT */
};

static GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_Fontfont_size16_Prop10 = {
   0xC0C1 /* first character */
  ,0xC0C1 /* last character  */
  ,&GUI_Fontfont_size16_CharInfo[ 92] /* address of first character */
  ,&GUI_Fontfont_size16_Prop11 /* pointer to next GUI_FONT_PROP_EXT */
};

static GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_Fontfont_size16_Prop9 = {
   0xBCF4 /* first character */
  ,0xBCF4 /* last character  */
  ,&GUI_Fontfont_size16_CharInfo[ 91] /* address of first character */
  ,&GUI_Fontfont_size16_Prop10 /* pointer to next GUI_FONT_PROP_EXT */
};

static GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_Fontfont_size16_Prop8 = {
   0xBCA4 /* first character */
  ,0xBCA4 /* last character  */
  ,&GUI_Fontfont_size16_CharInfo[ 90] /* address of first character */
  ,&GUI_Fontfont_size16_Prop9 /* pointer to next GUI_FONT_PROP_EXT */
};

static GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_Fontfont_size16_Prop7 = {
   0xBA85 /* first character */
  ,0xBA85 /* last character  */
  ,&GUI_Fontfont_size16_CharInfo[ 89] /* address of first character */
  ,&GUI_Fontfont_size16_Prop8 /* pointer to next GUI_FONT_PROP_EXT */
};

static GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_Fontfont_size16_Prop6 = {
   0xB839 /* first character */
  ,0xB839 /* last character  */
  ,&GUI_Fontfont_size16_CharInfo[ 88] /* address of first character */
  ,&GUI_Fontfont_size16_Prop7 /* pointer to next GUI_FONT_PROP_EXT */
};

static GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_Fontfont_size16_Prop5 = {
   0xACC4 /* first character */
  ,0xACC4 /* last character  */
  ,&GUI_Fontfont_size16_CharInfo[ 87] /* address of first character */
  ,&GUI_Fontfont_size16_Prop6 /* pointer to next GUI_FONT_PROP_EXT */
};

static GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_Fontfont_size16_Prop4 = {
   0x0030 /* first character */
  ,0x007F /* last character  */
  ,&GUI_Fontfont_size16_CharInfo[  7] /* address of first character */
  ,&GUI_Fontfont_size16_Prop5 /* pointer to next GUI_FONT_PROP_EXT */
};

static GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_Fontfont_size16_Prop3 = {
   0x002D /* first character */
  ,0x002E /* last character  */
  ,&GUI_Fontfont_size16_CharInfo[  5] /* address of first character */
  ,&GUI_Fontfont_size16_Prop4 /* pointer to next GUI_FONT_PROP_EXT */
};

static GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_Fontfont_size16_Prop2 = {
   0x002A /* first character */
  ,0x002B /* last character  */
  ,&GUI_Fontfont_size16_CharInfo[  3] /* address of first character */
  ,&GUI_Fontfont_size16_Prop3 /* pointer to next GUI_FONT_PROP_EXT */
};

static GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_Fontfont_size16_Prop1 = {
   0x001E /* first character */
  ,0x0020 /* last character  */
  ,&GUI_Fontfont_size16_CharInfo[  0] /* address of first character */
  ,&GUI_Fontfont_size16_Prop2 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT GUI_Fontfont_size16 = {
   GUI_FONTTYPE_PROP_EXT /* type of font    */
  ,16 /* height of font  */
  ,16 /* space of font y */
  ,1 /* magnification x */
  ,1 /* magnification y */
  ,{&GUI_Fontfont_size16_Prop1}
  ,14 /* Baseline */
  ,9 /* Height of lowercase characters */
  ,12 /* Height of capital characters */
};

